"""Top-5-per-shape library from N4a fresh archive."""
import torch

def key_softmax(*args) -> int:
    return 0

def autotune_softmax(*args) -> dict:
    _C = [
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['first', '', '', 'first'], 'num_sm_multiplier': 1, 'num_stages': 7, 'num_warps': 8, 'pid_type': 'persistent_blocked', 'range_flattens': [False], 'range_multi_buffers': [None], 'range_num_stages': [4], 'range_unroll_factors': [3], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['first', '', '', 'first'], 'num_stages': 7, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['first', '', '', 'last'], 'num_sm_multiplier': 2, 'num_stages': 7, 'num_warps': 2, 'pid_type': 'persistent_blocked', 'range_flattens': [False], 'range_multi_buffers': [None], 'range_num_stages': [4], 'range_unroll_factors': [3], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer'], 'load_eviction_policies': ['first', 'first', 'last', 'last'], 'num_stages': 1, 'num_warps': 32, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', 'last', 'last'], 'num_stages': 2, 'num_warps': 32, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', '', ''], 'num_stages': 1, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', 'last', 'last'], 'num_stages': 2, 'num_warps': 16, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer'], 'load_eviction_policies': ['first', '', 'first', 'first'], 'num_stages': 5, 'num_warps': 1, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', '', ''], 'num_stages': 2, 'num_warps': 8, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', '', 'last'], 'num_stages': 2, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['last', 'first', '', ''], 'num_stages': 5, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['last', 'first', '', 'first'], 'num_stages': 5, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor'], 'load_eviction_policies': ['first', '', 'last', ''], 'num_stages': 6, 'num_warps': 1, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor'], 'load_eviction_policies': ['', '', 'last', ''], 'num_stages': 6, 'num_warps': 1, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['first', '', 'last', 'first'], 'num_stages': 6, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['last', '', 'first', ''], 'num_stages': 3, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['last', '', '', ''], 'num_stages': 4, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', 'last', ''], 'num_stages': 1, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', 'last', ''], 'num_stages': 2, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['first', '', 'first', 'last'], 'num_stages': 7, 'num_warps': 2, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['last', '', '', 'last'], 'num_stages': 6, 'num_warps': 2, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'load_eviction_policies': ['last', '', 'first', 'last'], 'num_stages': 6, 'num_warps': 2, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['last', '', 'first', 'last'], 'num_stages': 6, 'num_warps': 2, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['first', '', 'first', 'first'], 'num_stages': 6, 'num_warps': 2, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['first', '', '', 'first'], 'maxnreg': 128, 'num_sm_multiplier': 32, 'num_stages': 6, 'num_warps': 2, 'pid_type': 'persistent_interleaved', 'range_flattens': [False], 'range_multi_buffers': [True], 'range_num_stages': [0], 'range_unroll_factors': [4], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['', '', '', 'first'], 'maxnreg': 128, 'num_sm_multiplier': 32, 'num_stages': 6, 'num_warps': 4, 'pid_type': 'persistent_interleaved', 'range_flattens': [False], 'range_multi_buffers': [True], 'range_num_stages': [0], 'range_unroll_factors': [3], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer'], 'load_eviction_policies': ['first', '', 'first', 'first'], 'num_stages': 6, 'num_warps': 8, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor'], 'load_eviction_policies': ['', 'first', 'last', ''], 'num_stages': 5, 'num_warps': 8, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor'], 'load_eviction_policies': ['', 'first', 'last', ''], 'num_stages': 4, 'num_warps': 8, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'load_eviction_policies': ['', 'last', 'last', ''], 'num_stages': 2, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', 'last', 'last'], 'num_stages': 2, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor'], 'load_eviction_policies': ['', 'last', 'last', ''], 'num_stages': 2, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer'], 'load_eviction_policies': ['', 'last', 'last', 'last'], 'num_stages': 2, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', 'last', ''], 'num_stages': 2, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
    ]
    return _C[key_softmax(*args)]
