"""Top-5-per-shape library from N4a fresh archive."""
import torch

def key_layer_norm(*args) -> int:
    return 0

def autotune_layer_norm(*args) -> dict:
    _C = [
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor'], 'load_eviction_policies': ['last', '', 'first', 'last', '', '', '', 'last'], 'num_stages': 3, 'num_warps': 8, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [512]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer'], 'load_eviction_policies': ['first', 'last', 'first', 'first', 'first', 'last', 'first', 'first'], 'num_stages': 8, 'num_warps': 8, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [512]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor'], 'load_eviction_policies': ['last', '', 'first', 'last', '', '', '', 'last'], 'num_stages': 3, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'load_eviction_policies': ['first', '', 'first', 'last', 'first', '', '', 'last'], 'num_stages': 3, 'num_warps': 16, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'load_eviction_policies': ['first', '', 'first', 'last', 'first', '', '', 'last'], 'num_stages': 4, 'num_warps': 2, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['', '', 'first', 'first', '', 'first', 'first', 'first'], 'num_stages': 4, 'num_warps': 8, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor'], 'load_eviction_policies': ['first', 'first', 'last', '', 'first', '', '', ''], 'num_stages': 7, 'num_warps': 16, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor'], 'load_eviction_policies': ['first', 'first', 'last', 'last', 'first', '', '', ''], 'num_stages': 7, 'num_warps': 8, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['', '', 'first', 'first', '', 'first', 'first', 'last'], 'num_stages': 4, 'num_warps': 16, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['', '', 'first', 'first', '', 'first', '', 'first'], 'num_stages': 4, 'num_warps': 16, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', '', 'first', '', '', 'first', ''], 'num_stages': 1, 'num_warps': 8, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', 'first', 'first', '', '', 'first', 'last'], 'num_stages': 4, 'num_warps': 8, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['first', 'first', 'first', 'first', 'first', 'first', 'last', 'first'], 'num_stages': 1, 'num_warps': 8, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'load_eviction_policies': ['first', 'last', 'first', 'first', '', '', 'last', 'last'], 'num_stages': 1, 'num_warps': 8, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['first', '', 'first', 'first', '', '', '', 'last'], 'num_stages': 1, 'num_warps': 8, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor'], 'load_eviction_policies': ['first', 'first', 'last', '', 'first', '', '', ''], 'num_stages': 7, 'num_warps': 2, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor'], 'load_eviction_policies': ['first', 'first', 'last', '', 'first', '', '', ''], 'num_stages': 6, 'num_warps': 2, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['last', 'last', '', '', 'last', 'last', 'first', 'last'], 'num_stages': 1, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [2048]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['', '', '', '', '', 'last', '', ''], 'num_stages': 1, 'num_warps': 8, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'load_eviction_policies': ['first', 'first', 'last', '', 'first', '', '', ''], 'num_stages': 7, 'num_warps': 8, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', 'first', '', '', '', '', ''], 'num_stages': 1, 'num_warps': 2, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [1024]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', '', '', '', 'first', '', ''], 'num_stages': 1, 'num_warps': 2, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [1024]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', '', '', '', '', '', ''], 'num_stages': 1, 'num_warps': 1, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [1024]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', 'first', 'last', '', '', '', 'first'], 'num_stages': 3, 'num_warps': 2, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [512]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', 'first', 'last', '', '', '', 'first'], 'num_stages': 3, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [512]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor'], 'load_eviction_policies': ['', '', '', '', '', '', '', ''], 'num_stages': 1, 'num_warps': 1, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [1024]},
        {'atomic_indexing': [], 'block_sizes': [1], 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', 'first', 'last', '', '', '', 'first'], 'num_stages': 3, 'num_warps': 2, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [1024]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', 'first', 'last', '', 'last', '', 'first'], 'num_stages': 3, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [2048]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', 'first', 'last', '', '', '', 'first'], 'num_stages': 3, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [1024]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', '', '', '', '', '', 'last'], 'num_stages': 1, 'num_warps': 1, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [None]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', 'first', 'last', '', '', '', 'first'], 'num_stages': 4, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [1024]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', 'first', 'last', '', '', '', 'first'], 'num_stages': 2, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [1024]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['', '', 'first', 'last', '', '', '', 'last'], 'num_stages': 2, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [1024]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['', 'last', 'first', 'last', 'last', 'last', 'first', 'first'], 'num_stages': 6, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [1024]},
        {'atomic_indexing': [], 'block_sizes': [2], 'indexing': ['pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer'], 'load_eviction_policies': ['', 'last', 'first', 'last', 'first', 'last', 'first', 'last'], 'num_stages': 6, 'num_warps': 4, 'pid_type': 'flat', 'range_flattens': [None], 'range_multi_buffers': [None], 'range_num_stages': [0], 'range_unroll_factors': [0], 'range_warp_specializes': [None], 'reduction_loops': [1024]},
    ]
    return _C[key_layer_norm(*args)]
